"""boshlang'ich sxema

Revision ID: 636a67b68354
Revises: 
Create Date: 2026-09-25 11:00:52.448666
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '636a67b68354'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('last_load_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('feature_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feature_name')
    )
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_registry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_key', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('algorithm', sa.String(length=128), nullable=False),
    sa.Column('training_dataset', sa.String(length=128), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('threshold', sa.JSON(), nullable=False),
    sa.Column('drift', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_key', 'version', name='uq_model_version')
    )
    op.create_table('regions',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('short_name', sa.String(length=32), nullable=False),
    sa.Column('geo_key', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sectors',
    sa.Column('id', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('icon', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('data_lineage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('source_record_id', sa.String(length=64), nullable=True),
    sa.Column('target_table', sa.String(length=64), nullable=False),
    sa.Column('target_record_id', sa.String(length=64), nullable=True),
    sa.Column('transformation', sa.String(length=128), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('region_id', sa.String(length=8), nullable=False),
    sa.Column('sector_id', sa.String(length=16), nullable=False),
    sa.Column('size_group', sa.String(length=16), nullable=False),
    sa.Column('stir', sa.String(length=9), nullable=False),
    sa.Column('org_form', sa.String(length=16), nullable=False),
    sa.Column('registered_at', sa.Date(), nullable=False),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_records', sa.Integer(), nullable=False),
    sa.Column('history_months', sa.Integer(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_subjects_region_id'), ['region_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subjects_sector_id'), ['sector_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('region_id', sa.String(length=8), nullable=True),
    sa.Column('organization', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('region_id', sa.String(length=8), nullable=False),
    sa.Column('risk_type', sa.String(length=4), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('analyst_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_region_id'), ['region_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_subject_id'), ['subject_id'], unique=False)

    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('old_value', sa.JSON(), nullable=True),
    sa.Column('new_value', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_at', ['at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)

    op.create_table('imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_format', sa.String(length=8), nullable=False),
    sa.Column('stage', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('accepted', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('duplicates', sa.Integer(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('mapping', sa.JSON(), nullable=False),
    sa.Column('dq', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monthly_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('tx_count', sa.Integer(), nullable=True),
    sa.Column('avg_check', sa.Float(), nullable=True),
    sa.Column('tax_index', sa.Float(), nullable=True),
    sa.Column('registry_turnover', sa.Float(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'period', name='uq_metric_subject_period')
    )
    with op.batch_alter_table('monthly_metrics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_monthly_metrics_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_monthly_metrics_subject_id'), ['subject_id'], unique=False)

    op.create_table('relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('rel_type', sa.String(length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('since', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_relations_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_relations_target_id'), ['target_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('report_type', sa.String(length=16), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('data_version', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('confidence_value', sa.Float(), nullable=False),
    sa.Column('dq_score', sa.Float(), nullable=False),
    sa.Column('dq_dimensions', sa.JSON(), nullable=False),
    sa.Column('primary_risk_type', sa.String(length=4), nullable=False),
    sa.Column('risk_types', sa.JSON(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('expert_status', sa.String(length=24), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('data_version', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_scores_dq_score'), ['dq_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_scores_expert_status'), ['expert_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_scores_primary_risk_type'), ['primary_risk_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_scores_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_scores_subject_id'), ['subject_id'], unique=True)

    op.create_table('expert_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('score_at_decision', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expert_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expert_decisions_subject_id'), ['subject_id'], unique=False)

    op.create_table('risk_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_score_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('feature', sa.String(length=48), nullable=False),
    sa.Column('factor', sa.String(length=96), nullable=False),
    sa.Column('risk_type', sa.String(length=4), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('baseline_low', sa.Float(), nullable=True),
    sa.Column('baseline_high', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('deviation', sa.String(length=8), nullable=False),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['risk_score_id'], ['risk_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('risk_factors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_factors_risk_score_id'), ['risk_score_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_factors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_factors_risk_score_id'))

    op.drop_table('risk_factors')
    with op.batch_alter_table('expert_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expert_decisions_subject_id'))

    op.drop_table('expert_decisions')
    with op.batch_alter_table('risk_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_scores_subject_id'))
        batch_op.drop_index(batch_op.f('ix_risk_scores_score'))
        batch_op.drop_index(batch_op.f('ix_risk_scores_primary_risk_type'))
        batch_op.drop_index(batch_op.f('ix_risk_scores_expert_status'))
        batch_op.drop_index(batch_op.f('ix_risk_scores_dq_score'))

    op.drop_table('risk_scores')
    op.drop_table('reports')
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_relations_target_id'))
        batch_op.drop_index(batch_op.f('ix_relations_source_id'))

    op.drop_table('relations')
    with op.batch_alter_table('monthly_metrics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_monthly_metrics_subject_id'))
        batch_op.drop_index(batch_op.f('ix_monthly_metrics_period'))

    op.drop_table('monthly_metrics')
    op.drop_table('imports')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))
        batch_op.drop_index('ix_audit_at')

    op.drop_table('audit_log')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_subject_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_region_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_detected_at'))

    op.drop_table('alerts')
    op.drop_table('users')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_sector_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_region_id'))
        batch_op.drop_index(batch_op.f('ix_subjects_code'))

    op.drop_table('subjects')
    op.drop_table('data_lineage')
    op.drop_table('settings')
    op.drop_table('sectors')
    op.drop_table('regions')
    op.drop_table('model_registry')
    op.drop_table('jobs')
    op.drop_table('feature_registry')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
